import { Control } from './Control';
import './globals.css';
import Link from 'next/link';

export const metadata = {
    title: 'Web tutorials',
    description: 'Generated by mary',
};

export default async function RootLayout({ children }) {
    const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + `topics`, { cache: 'no-cache' });
    const topics = await resp.json();
    return (
        <html>
            <body>
                <h1>
                    <Link href="/">HOME</Link>
                </h1>
                <ol>
                    {topics.map((topic) => {
                        return (
                            <li key={topic.id}>
                                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                            </li>
                        );
                    })}
                </ol>
                {children}
                {/* page에서만든컨텐츠는여기 */}
                <Control />
            </body>
        </html>
    );
}
