import './globals.css';
import Link from 'next/link';

export const metadata = {
    title: 'Web tutorials',
    description: 'Generated by mary',
};

export default async function RootLayout({ children }) {
    const resp = await fetch('http://localhost:9999/topics');
    const topics = await resp.json();
    return (
        <html>
            <body>
                <h1>
                    <Link href="/">WEB</Link>
                </h1>
                <ol>
                    {topics.map((topic) => {
                        return (
                            <li key={topic.id}>
                                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                            </li>
                        );
                    })}
                </ol>
                {children}
                {/* page에서만든컨텐츠는여기 */}
                <ul>
                    <li>
                        <Link href="/create">Create</Link>
                    </li>
                    <li>
                        <Link href="/update/1">Update</Link>
                    </li>
                    <li>
                        <button>delete</button>
                    </li>
                </ul>
            </body>
        </html>
    );
}
